apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "jobready.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # .Values.postgres.storage resolves to "5Gi" from values.yaml
      # You can override: helm install jobready . --set postgres.storage=20Gi
      storage: {{ .Values.postgres.storage }}
