apiVersion: v2
name: jobready
description: JobReady — AI-powered job application tracker (Team GenOps, TUM AET DevOps 2026)
type: application         

version: 0.1.0            # Chart version. Bump this when you change templates.
appVersion: "0.1.0"       # Application version. Shown by "helm list".
