apiVersion: v1
kind: Service
metadata:
  name: document
  namespace: {{ .Values.global.namespace }}
  labels:
    app: document
    monitoring: "true"
    {{- include "jobready.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: document
  ports:
    - name: http
      port: {{ .Values.document.port }}
      targetPort: {{ .Values.document.port }}
      protocol: TCP
